# Generated by Django 2.0.6 on 2018-06-22 00:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spaceSession', '0002_auto_20180621_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='step_three',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
