# Generated by Django 2.0.6 on 2018-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceSession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step_four',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step_one',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step_three',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='step_two',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
